module.exports = {
  apps: [
    {
      name: "traco-mcp",
      script: "dist/src/index.js",
      cwd: __dirname,
      interpreter: "node",
      node_args: "--env-file=.env --enable-source-maps",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      min_uptime: 10000,
      max_restarts: 10,
      max_memory_restart: "256M",
      time: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "traco-discord",
      script: "dist/src/discord-bot.js",
      cwd: __dirname,
      interpreter: "node",
      node_args: "--env-file=.env --enable-source-maps",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      restart_delay: 5000,
      min_uptime: 10000,
      max_restarts: 10,
      max_memory_restart: "256M",
      time: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "traco-google-chat",
      script: "dist/src/google-chat-index.js",
      cwd: __dirname,
      interpreter: "node",
      node_args: "--env-file=.env --enable-source-maps",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      restart_delay: 5000,
      min_uptime: 10000,
      max_restarts: 10,
      max_memory_restart: "256M",
      time: true,
      env: { NODE_ENV: "production" },
    },
  ],
};
